server:
  port: 8089

#是否开启 swagger-ui
swagger:
  enabled: true

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 3000MB
      max-request-size: 3000MB

# 文件存储路径
file:
  mac:
    path: ~/file/
    imageRootPath: ~/file/image_root/ #压缩包解压缩文件夹
  linux:
    path: /home/aias/file/
    imageRootPath: /home/aias/file/image_root/ #压缩包解压缩文件夹
  windows:
    path: file:///D:/aias/file/
    imageRootPath: file:///D:/aias/file/image_root/ #压缩包解压缩文件夹
  # 文件大小 /M
  maxSize: 3000

image:
  #  path: /Users/calvin/Documents/image_root/ #图片存放文件夹
  baseurl: http://127.0.0.1:8089/images/

#Face
face:
  # n 帧取一帧 (跳帧)
  mod: 3
  # 是否保存人脸抠图
  saveDetectedFace: true
  # 图像缩放比，越小速度越快，精度越低，需根据场景调优
  shrink: 0.5
  # 检测结果的置信度过滤阈值
  threshold: 0.7
  # 人脸检测模型
  det: models/face_detection.zip
  # 人脸特征提取模型
  feature: models/face_feature.zip

# Vector Engine - Milvus
search:
  host: 127.0.0.1
  port: 19530

  # https://milvus.io/cn/docs/v2.0.0/build_index.md
  # https://milvus.io/cn/docs/v2.0.0/metric.md#floating
  # For floating point vectors:
  #  IVF_FLAT
  #  IVF_SQ8
  #  IVF_PQ
  #  HNSW
  #  ANNOY
  #  RHNSW_FLAT
  #  RHNSW_PQ
  #  RHNSW_SQ
  # For binary vectors:
  #  BIN_IVF_FLAT
  indexType: IVF_FLAT
  metricType: L2

  nprobe: 256
  nlist: 16384
  dimension: 512 # dimension of each vector
  collectionName: video_images #collection name
  partitionName: p1